### ISSUE TITLE
Cairn.info erreur 500

### ISSUE THREAD

**Issue by Marcool04** [SCD-Aix-Marseille-Universite/lama-addons#6]
Bonjour,
J'utilise la dernière version (au 17 avril) de lama, dans Firefox.
Depuis peu, lorsqu'on essaie de récupérer le texte intégral d'un document sur cairn.info, on rencontre une erreur 500 (qui est une erreur serveur, mais doit provenir plutôt de univ-amu.fr que de cairn.info, car de leur côté tout fonctionne bien).
Par exemple, sur 
https://www-cairn-info.lama.univ-amu.fr/revue-espace-geographique-2014-1-page-81.htm?contenu=article
il y a un lien "Télécharger" qui pointe vers :
https://www-cairn-info.lama.univ-amu.fr/load_pdf.php?ID_ARTICLE=EG_431_0081&download=1
et cette page renvoie `500 Internal Server Error`.
Merci d'avance de votre aide.
Et bravo pour cette super-pratique petit addon !
Bien à vous,
Mark.

**Comment by eurruby** [comment]
Je ne reproduit pas l'anomalie aujourd'hui. Est-ce toujours d'actualité ?
Il ne s'agit pas à priori d'un problème lié à l'extension puisqu'elle ne fait qu'établir la passerelle avec le serveur d'accès (proxy) AMU.

**Comment by Marcool04** [comment]
En effet, le problème semble résolu ! Et effectivement, j'aurais du me douter que ça se situait plutôt côté proxy vu le code de l'erreur… Où aurait-il été plus pertinent de rapporter le problème ? Désolé pour le dérangement en tous les cas, et merci pour la réponse.
